from django.db import models
from django.contrib.auth.models import User

class Prediction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    gender = models.IntegerField()
    air_pollution = models.IntegerField()
    alcohol_use = models.IntegerField()
    dust_allergy = models.IntegerField()
    occupational_hazards = models.IntegerField()
    genetic_risk = models.IntegerField()
    chronic_lung_disease = models.IntegerField()
    balanced_diet = models.IntegerField()
    obesity = models.IntegerField()
    smoking = models.IntegerField()
    passive_smoker = models.IntegerField()
    chest_pain = models.IntegerField()
    coughing_of_blood = models.IntegerField()
    fatigue = models.IntegerField()
    weight_loss = models.IntegerField()
    shortness_of_breath = models.IntegerField()
    wheezing = models.IntegerField()
    swallowing_difficulty = models.IntegerField()
    clubbing_of_finger_nails = models.IntegerField()
    frequent_cold = models.IntegerField()
    dry_cough = models.IntegerField()
    snoring = models.IntegerField()
    diagnosis = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
