# Generated by Django 4.1.7 on 2023-03-30 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_delete_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('air_pollution', models.IntegerField()),
                ('alcohol_use', models.IntegerField()),
                ('dust_allergy', models.IntegerField()),
                ('occupational_hazards', models.IntegerField()),
                ('genetic_risk', models.IntegerField()),
                ('chronic_lung_disease', models.IntegerField()),
                ('balanced_diet', models.IntegerField()),
                ('obesity', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('passive_smoker', models.IntegerField()),
                ('chest_pain', models.IntegerField()),
                ('coughing_of_blood', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('weight_loss', models.IntegerField()),
                ('shortness_of_breath', models.IntegerField()),
                ('wheezing', models.IntegerField()),
                ('swallowing_difficulty', models.IntegerField()),
                ('clubbing_of_finger_nails', models.IntegerField()),
                ('frequent_cold', models.IntegerField()),
                ('dry_cough', models.IntegerField()),
                ('snoring', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
